rvm:
  - ruby-head
  - jruby-head
  - jruby-19mode
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0
os:
  - linux
  - osx
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head
gemfile:
  - Gemfile

script: "bundle exec rake test"

env: TEST=true
