language: ruby
cache: bundler
sudo: false
env: TEST=true

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby-head

gemfile:
  - gemfiles/middleman-4.1.gemfile

matrix:
  include:
  - rvm: 2.2
    gemfile: gemfiles/middleman-4.0.gemfile
  - rvm: 2.2
    gemfile: gemfiles/middleman-head.gemfile
  - rvm: 2.2
    gemfile: gemfiles/sprockets-4.0.gemfile

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: 2.2
      gemfile: gemfiles/sprockets-4.0.gemfile
